-- Research report originals live in private Storage. Postgres only keeps
-- metadata and page text; embeddings are intentionally out of scope.

insert into storage.buckets (id, name, public)
values ('research-reports', 'research-reports', false)
on conflict (id) do nothing;

create table if not exists public.research_reports (
    id bigint generated by default as identity primary key,
    stock_code text not null references public.stocks(code),
    broker text not null,
    title text not null,
    published_on date not null,
    storage_path text not null unique,
    source_filename text not null,
    sha256 char(64) not null unique,
    page_count integer not null check (page_count > 0),
    file_size_bytes bigint not null check (file_size_bytes > 0),
    extraction_status text not null check (
        extraction_status in ('text_extracted', 'needs_ocr', 'failed')
    ),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists research_reports_stock_date_idx
    on public.research_reports (stock_code, published_on desc);

create table if not exists public.research_report_pages (
    id bigint generated by default as identity primary key,
    report_id bigint not null references public.research_reports(id) on delete cascade,
    page_number integer not null check (page_number > 0),
    text_content text not null,
    char_count integer not null check (char_count >= 0),
    extraction_method text not null default 'pdf_text' check (
        extraction_method in ('pdf_text', 'ocr')
    ),
    created_at timestamptz not null default now(),
    unique (report_id, page_number)
);

create index if not exists research_report_pages_report_idx
    on public.research_report_pages (report_id, page_number);

alter table public.research_reports enable row level security;
alter table public.research_report_pages enable row level security;

comment on table public.research_reports is
    'Private analyst-report metadata. PDF bytes remain in Supabase Storage.';
comment on table public.research_report_pages is
    'Page text only. Chunking and embeddings are created later by a separate RAG indexer.';
