begin;

create table public.news_clusters (
    id bigint generated by default as identity primary key,
    stock_code text not null references public.stocks(code) on delete cascade,
    kind text not null check (kind in ('company', 'market', 'info')),
    anchor_article_id bigint not null references public.articles(id) on delete restrict,
    representative_article_id bigint not null references public.articles(id) on delete restrict,
    centroid double precision[] not null,
    article_count integer not null default 1 check (article_count > 0),
    first_published_at timestamptz not null,
    last_active_at timestamptz not null,
    clustering_version text not null,
    summary_title text,
    factual_body text,
    summary_status text not null default 'pending'
        check (summary_status in ('pending', 'success', 'pending_retry')),
    summary_prompt_version text,
    summary_error text,
    summary_retry_count integer not null default 0 check (summary_retry_count >= 0),
    summary_next_retry_at timestamptz,
    summarized_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.news_cluster_assignments (
    article_id bigint not null references public.articles(id) on delete cascade,
    stock_code text not null references public.stocks(code) on delete cascade,
    cluster_id bigint references public.news_clusters(id) on delete cascade,
    kind text not null check (kind in ('company', 'market', 'info')),
    status text not null
        check (status in ('assigned_new', 'assigned_existing', 'pending_retry')),
    llm_called boolean not null default false,
    candidate_count integer not null default 0 check (candidate_count >= 0),
    assignment_reason text,
    error_code text,
    prompt_version text,
    retry_count integer not null default 0 check (retry_count >= 0),
    next_retry_at timestamptz,
    assigned_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (article_id, stock_code),
    check (
        (status = 'pending_retry' and cluster_id is null and next_retry_at is not null)
        or
        (status <> 'pending_retry' and cluster_id is not null and next_retry_at is null)
    )
);

create table public.news_article_processing (
    article_id bigint primary key references public.articles(id) on delete cascade,
    kind text check (kind in ('company', 'market', 'info')),
    status text not null check (status in ('processing', 'completed', 'pending_retry')),
    retry_count integer not null default 0 check (retry_count >= 0),
    next_retry_at timestamptz,
    last_error text,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index news_clusters_active_idx
    on public.news_clusters (stock_code, kind, last_active_at desc);
create index news_cluster_assignments_cluster_idx
    on public.news_cluster_assignments (cluster_id, assigned_at)
    where cluster_id is not null;
create index news_cluster_assignments_retry_idx
    on public.news_cluster_assignments (status, next_retry_at)
    where status = 'pending_retry';
create index news_article_processing_retry_idx
    on public.news_article_processing (status, next_retry_at)
    where status = 'pending_retry';
create index news_clusters_summary_retry_idx
    on public.news_clusters (summary_status, summary_next_retry_at)
    where summary_status in ('pending', 'pending_retry');

create trigger news_clusters_set_updated_at
before update on public.news_clusters
for each row execute function public.set_updated_at();
create trigger news_cluster_assignments_set_updated_at
before update on public.news_cluster_assignments
for each row execute function public.set_updated_at();
create trigger news_article_processing_set_updated_at
before update on public.news_article_processing
for each row execute function public.set_updated_at();

alter table public.news_clusters enable row level security;
alter table public.news_cluster_assignments enable row level security;
alter table public.news_article_processing enable row level security;

commit;
