-- DART 원본 보존·기업개황·일정·정정 연결·수집 감사용 비파괴 확장.
-- 기존 DART/뉴스 행은 삭제하거나 재작성하지 않는다.
begin;

alter table public.disclosures
    add column if not exists raw_document_path text,
    add column if not exists raw_text_length bigint,
    add column if not exists content_hash text,
    add column if not exists parse_status text not null default 'pending',
    add column if not exists parse_error text,
    add column if not exists original_rcept_no text,
    add column if not exists supersedes_rcept_no text,
    add column if not exists is_latest boolean not null default true,
    add column if not exists correction_status text not null default 'original';

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'disclosures_parse_status_check'
    ) then
        alter table public.disclosures add constraint disclosures_parse_status_check
            check (parse_status in ('pending', 'success', 'failed', 'not_selected'));
    end if;
    if not exists (
        select 1 from pg_constraint where conname = 'disclosures_correction_status_check'
    ) then
        alter table public.disclosures add constraint disclosures_correction_status_check
            check (correction_status in ('original', 'correction', 'cancelled', 'withdrawn'));
    end if;
    if not exists (
        select 1 from pg_constraint where conname = 'disclosures_original_rcept_no_fkey'
    ) then
        alter table public.disclosures add constraint disclosures_original_rcept_no_fkey
            foreign key (original_rcept_no) references public.disclosures(rcept_no)
            on delete set null deferrable initially deferred;
    end if;
    if not exists (
        select 1 from pg_constraint where conname = 'disclosures_supersedes_rcept_no_fkey'
    ) then
        alter table public.disclosures add constraint disclosures_supersedes_rcept_no_fkey
            foreign key (supersedes_rcept_no) references public.disclosures(rcept_no)
            on delete set null deferrable initially deferred;
    end if;
end $$;

create index if not exists disclosures_original_rcept_idx
    on public.disclosures (original_rcept_no, disclosed_at);
create index if not exists disclosures_latest_idx
    on public.disclosures (stock_code, is_latest, disclosed_at desc);
create index if not exists disclosures_parse_status_idx
    on public.disclosures (parse_status, raw_text_truncated);

create table if not exists public.company_profiles (
    stock_code text primary key references public.stocks(code) on delete cascade,
    corp_name text,
    corp_name_eng text,
    stock_name text,
    ceo_nm text,
    corp_cls text,
    jurir_no text,
    bizr_no text,
    adres text,
    hm_url text,
    ir_url text,
    phn_no text,
    fax_no text,
    induty_code text,
    est_dt date,
    acc_mt text,
    raw_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.corporate_events (
    id bigint generated by default as identity primary key,
    stock_code text not null references public.stocks(code) on delete cascade,
    event_type text not null,
    title text not null,
    announced_at timestamptz,
    event_date date,
    event_end_date date,
    start_time time,
    end_time time,
    location text,
    amount bigint,
    status text not null default 'scheduled',
    rcept_no text not null references public.disclosures(rcept_no) on delete cascade,
    supersedes_rcept_no text,
    source_url text,
    normalized_data jsonb not null default '{}'::jsonb,
    raw_text text,
    parse_status text not null default 'success',
    parse_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (stock_code, event_type, rcept_no)
);

create index if not exists corporate_events_stock_date_idx
    on public.corporate_events (stock_code, event_date desc);

create table if not exists public.dart_collection_runs (
    id bigint generated by default as identity primary key,
    run_key text not null unique,
    mode text not null,
    status text not null default 'running',
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    stats jsonb not null default '{}'::jsonb,
    error text
);

create table if not exists public.dart_collection_api_results (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.dart_collection_runs(id) on delete cascade,
    stock_code text not null references public.stocks(code) on delete cascade,
    data_group text not null,
    source_api text not null,
    request_key text not null,
    result_status text not null,
    dart_status text,
    row_count integer not null default 0,
    error text,
    requested_at timestamptz not null default now(),
    unique (run_id, stock_code, data_group, source_api, request_key)
);

create index if not exists dart_collection_api_results_lookup_idx
    on public.dart_collection_api_results (stock_code, data_group, source_api, requested_at desc);

drop trigger if exists company_profiles_set_updated_at on public.company_profiles;
create trigger company_profiles_set_updated_at
    before update on public.company_profiles
    for each row execute function public.set_updated_at();

drop trigger if exists corporate_events_set_updated_at on public.corporate_events;
create trigger corporate_events_set_updated_at
    before update on public.corporate_events
    for each row execute function public.set_updated_at();

alter table public.company_profiles enable row level security;
alter table public.corporate_events enable row level security;
alter table public.dart_collection_runs enable row level security;
alter table public.dart_collection_api_results enable row level security;

commit;
